### ISSUE TITLE
Extension terminal doesn't load

### ISSUE THREAD

**Issue by gammaray05** [Ansuel/tch-nginx-gui#1003]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
[DebugHelper2020-11-13-0105.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/5533928/DebugHelper2020-11-13-0105.tar.gz)

Device Model: DGA4132, 2.2.2-001
Gui Version: 9.5.38-ba81e28c

Description of problem: When installing an extension, nothing happens in the terminal.

How to reproduce (if possible):

Media/Photos (if possible): 
![image](https://user-images.githubusercontent.com/45374198/99011688-f601fe00-254c-11eb-8452-7c37e1529c91.png)

**Comment by FrancYescO** [comment]
already fixed in dev version

**Comment by lorenzocanale-LC** [comment]
There is still something wrong, on DGA4132 2.2.1 GUI Version 9.6.10-663c1ee8, the terminal still doesn't load on a fresh GUI install, and even after an upgradegui (by the way, upgradegui takes forever, it hangs on  "Copying file to permanent dir...") from ssh, the terminal start working only when switching and updating to DEV
