### ISSUE TITLE
Error in rootdevice firewall rule check

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#148]
Probably the check of the rule before delete is not written good

```
root@OpenWrt:~# /etc/init.d/rootdevice force
Root Script: Rooting in progress...
/etc/rc.common: line 1: uci get firewall.wan_SSH_rule1: not found
/etc/rc.common: line 1: uci get firewall.wan_SSH_rule5: not found
interface wan has no physdev or physdev has no suitable ip
```

**Comment by Ansuel** [comment]
Fixed

**Comment by FrancYescO** [comment]
Seems still get the error during execution if the rules are missing
```
root@OpenWrt:~# /etc/init.d/rootdevice force
Root Script: Rooting in progress...
Command failed: Not found
/etc/rc.common: line 1: uci get -q firewall.wan_SSH_rule1: not found
/etc/rc.common: line 1: uci get -q firewall.wan_SSH_rule5: not found
interface wan has no physdev or physdev has no suitable ip
ping: sendto: Network is unreachable
root@OpenWrt:~#
```
